apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-delete-task-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-delete-task-api
  template:
    metadata:
      labels:
        app: todo-delete-task-api
    spec:
      containers:
      - name: todo-delete-task-api
        image: devopsinsidersacr235.azurecr.io/todo-delete-task-api:v4
        ports:
        - containerPort: 80
